### ISSUE TITLE
Should a `Toggle`'s variant property be optional?

### ISSUE THREAD

**Issue by elliott-nutmeg** [Unleash/unleash-proxy-client-swift#7]
@FredrikOseberg I'm not sure if there are changes in the newly released Unleash Proxy library but is it possible that a toggle is returned without a variant? Hitting our Unleash service directly the `variants` property can be `null` in which case I think the toggle.variant should be an optional `Variant?`. I've seen some `The data couldn’t be read because it is missing.` errors logged to the console when running the unleash-proxy-client-swift which look to be json decoding related and wondered if this was due to a toggle missing a variant.

**Comment by FredrikOseberg** [comment]
@elliott-nutmeg 

Hey there. It's possible for the unleash-server endpoints to return toggles without variants, however the [unleash-proxy](https://github.com/Unleash/unleash-proxy) which we open sourced a while back will add variant information even if it's missing, in order to provide security for people who use languages without type safety. 

You can verify this by calling towards our demo proxy: 

```
curl -H "Content-Type: application/json" \
     -H "Authorization: proxy-123" https://app.unleash-hosted.com/demo/proxy
```

If a toggle does not have any variants it will be set to: 

```
"name": "disabled",
"enabled": false
```

Which version of the proxy are you using?

**Comment by elliott-nutmeg** [comment]
Thanks for the quick reply @FredrikOseberg. So we currently run our own proxy using the Unleash Client `unleash-client` which explains this difference. I've found the behaviour you describe here https://github.com/Unleash/unleash-client-node/blob/10d24ef3db68acd1580a2a82332f446aa8032cf1/src/variant.ts#L35. I'll take a look at what we're doing and close this issue for now. Thanks for your help!
